"""Trusted result contracts, additive to old evidence and message payloads."""
def extend_schemas(result):
    from .openapi import obj,ref,array,STRING,BOOL,ID,nullable
    states=['not_started','in_flight','confirmed','partial','reused_current_run','historical_evidence','unknown','rejected','cancelled']
    result['DataUsageV1']=obj({'status':{'enum':states},'queried':nullable(BOOL),'attempted':BOOL,'may_have_sent':BOOL,'new_call_count':{'type':'integer','minimum':0},'reuse_count':{'type':'integer','minimum':0},'source_data_run_id':nullable(ID),'modules':array(obj({'module':STRING,'status':STRING,'reserved':BOOL,'response_confirmed':BOOL},('module','status','reserved','response_confirmed'))),'basis':STRING},('status','queried','attempted','may_have_sent','new_call_count','reuse_count','source_data_run_id','modules','basis'))
    result['DataUsageV1']['properties']['modules']['items']['properties'].update({k:{'type':'integer','minimum':0} for k in ('reservation_count','dispatch_attempts','response_count')})
    result['DataUsageV1']['properties']['modules']['items']['properties']['call_id']=STRING
    result['ClaimV1']=obj({'schema':{'const':'peixian.claim'},'version':{'const':'1.0'},'claim_id':ID,'type':{'enum':['fact','computed','gap']},'template_id':STRING,'agent_id':STRING,'subject_refs':array(STRING),'statement':STRING,'protected_fields':{'type':'object','additionalProperties':True},'source_ids':array(STRING),'rule':nullable(obj({'id':STRING,'version':STRING},('id','version'))),'verification_status':{'const':'approved'},'source_run_id':ID},('schema','version','claim_id','type','template_id','agent_id','subject_refs','statement','protected_fields','source_ids','rule','verification_status','source_run_id'))
    result['NarrativeReviewV1']=obj({'status':{'enum':['verified','unverified','conflicted','not_generated']},'text':nullable(STRING),'claim_refs':array(ID),'conflicts':array(obj({'code':STRING,'message':STRING},('code','message'))),'review_version':STRING,'coverage':STRING},('status','text','claim_refs','conflicts','review_version','coverage'))
    result['TrustedResultV2']=obj({'schema':{'const':'peixian.analysis-result'},'version':{'const':'2.0'},'run_id':ID,'agent':ref('AgentIdentity'),'task':{'type':'object','additionalProperties':True},'data_environment':{'enum':['synthetic','acceptance_real']},'data_usage':ref('DataUsageV1'),'claims':array(ref('ClaimV1')),'records':array({'type':'object','additionalProperties':True}),'missing':array(STRING),'narrative':ref('NarrativeReviewV1'),'versions':{'type':'object','additionalProperties':True},'generated_at':{'type':'string','format':'date-time'}},('schema','version','run_id','agent','task','data_environment','data_usage','claims','records','missing','narrative','versions','generated_at'))
    result['ControlledAnswerItem']=obj({'text':STRING,'claim_id':ID,'source_run_id':ID,'source_ids':array(STRING)},('text','claim_id','source_run_id','source_ids'))
    result['ControlledAnswer']=obj({'version':{'const':'controlled-zh-v1'},'status':{'enum':['ready','partial','needs_input','unavailable']},'summary':STRING,'items':array(ref('ControlledAnswerItem')),'missing':array(STRING),'next_steps':array(STRING)},('version','status','summary','items','missing','next_steps'))
    result['TrustedResultV2']['properties']['answer']=ref('ControlledAnswer')
    result['SourceEvidence']=obj({'id':ID,'label':STRING,'content':STRING,'occurred_at':nullable(STRING),'time_semantics':STRING,'source_run_id':ID,'record_id':STRING,'claim_id':ID,'snapshot_id':STRING},('id','label','content','source_run_id','record_id','claim_id','snapshot_id'))
    result['SourceDetail']=obj({'version':{'const':'source-detail-v1'},'run_id':ID,'evidence':ref('SourceEvidence'),'record':{'type':'object','additionalProperties':True},'versions':{'type':'object','additionalProperties':True}},('version','run_id','evidence','record','versions'))
    result['SourceClue']=obj({'id':ID,'type':{'enum':['observation','person','place','night','funds','vehicle']},'title':STRING,'headline':STRING,'summary':STRING,'discoveries':array(STRING),'verification':{'const':'source_fields'},'evidence':array(ref('SourceEvidence')),'source_run_id':ID,'source_ids':array(STRING),'claim_ids':array(ID),'missing':array(STRING)},('id','type','title','headline','summary','discoveries','evidence','source_ids','claim_ids','missing'))
    result['TrustedResultV2']['properties']['presentation']=obj({'version':{'const':'source-clues-v1'},'status':{'enum':['ready','partial','empty']},'revision':STRING,'clues':array(ref('SourceClue')),'missing':array(STRING)},('version','status','revision','clues','missing'))
    result['PersonTableAnswer']=obj({'markdown':STRING,'run_id':ID,'version':{'enum':['person-tables-v1','person-tables-v2','person-tables-v3']},'status':STRING,'person_ref':nullable(STRING),'basic':array({'type':'object'}),'conclusions':array({'type':'object'}),'evidence':array({'type':'object'}),'suggestions':array({'type':'object'}),'next_question':nullable({'type':'object','additionalProperties':True}),'missing':array(STRING),'preview_count':{'type':'integer'},'total':{'type':'integer'},'source_runs':array(ID),'selection_status':STRING,'scoring':nullable({'type':'object','additionalProperties':True}),'ranking':nullable({'type':'object','additionalProperties':True}),'case_checks':nullable({'type':'object','additionalProperties':True}),'coverage':nullable({'type':'object','additionalProperties':True}),'direction':STRING,'case_type':nullable(STRING)},('version','basic','conclusions','evidence','suggestions','missing','preview_count','total'))
    result['PersonTableAnswer']['properties']['layout_version']=nullable(STRING)
    result['TrustedResultV2']['properties']['answer_view']=ref('PersonTableAnswer')
    result['TrustedResultPending']=obj({'schema':{'const':'peixian.analysis-result'},'version':{'const':'2.0'},'run_id':ID,'status':{'const':'pending'},'data_environment':{'enum':['synthetic','acceptance_real']},'data_usage':ref('DataUsageV1')},('schema','version','run_id','status','data_environment','data_usage'))
    result['TrustedResultLegacy']=obj({'schema':{'const':'peixian.analysis-result'},'version':{'const':'legacy'},'run_id':ID,'status':{'const':'legacy'},'result':{'type':'null'}},('schema','version','run_id','status','result'))
    result['TrustedResultResponse']={'oneOf':[ref('TrustedResultV2'),ref('TrustedResultPending'),ref('TrustedResultLegacy')]}
    result['RunClaims']=obj({'run_id':ID,'result_version':STRING,'status':{'enum':['final','pending','legacy']},'items':array(ref('ClaimV1'))},('run_id','result_version','status','items'))
    result['RunDataUsage']=obj({'run_id':ID,'result_version':STRING,'data_usage':nullable(ref('DataUsageV1'))},('run_id','result_version','data_usage'))
    return result
