import { render } from "solid-js/web"
import App from "./App"
import "../../ui/src/styles/theme.css"
import "./styles.css"
import "./chat-polish.css"
import "./visual-polish.css"
import "./typography.css"
import "./right-rail.css"
import "./chat-dialogue-v2.css"
render(() => <App />, document.getElementById("root")!)
